### ISSUE TITLE
Customize which attribute changes are considered a manual change

### ISSUE THREAD

**Issue by mikeage** [danobot/entity-controller#109]
See #98 for the initial discussion

**Is your feature request related to a problem? Please describe.**
Currently, any manual change to an entity that is `ON` is considered as a manual change that, as per requirement 3.2, puts EC in a `blocked` state. This feature request is for the ability to ignore certain changes.

Specifically, in my case, I use https://github.com/claytonjn/hass-circadian_lighting, which adjusts brightness and color temperature over the course of the day. I don't want these changes to be considered as manual changes that would disable EC.

**Describe the solution you'd like**
```yaml
  mtn_office:
    sensor: binary_sensor.office_motion
    trigger_on_activate: light.office_led
    delay: 120
    state_attributes_ignore:
        - brightness
        - color_temp
```

**Describe alternatives you've considered**
ignoring it :-)

**Additional context**
n/a
