### ISSUE TITLE
Using a group as controlled entity doesn't work.

### ISSUE THREAD

**Issue by jwelter1971** [danobot/entity-controller#115]
## Description
When using a group as a controlled entity it will not be turned on/off.

## Configuration
```
motion_night_outdoor:
   sensors:
      - group.house_exterior_activity
   entities: 
      - group.outdoor_lights
   delay: 600
   sensor_type: duration
   start_time: sunset 
   end_time: sunrise 

```
### Expected behavior
group.outdoor_lights to turn on

### Actual Behaviour
No lights on

Note: Swapping out the group.outdoor_lights to the 3 entities it contains works fine:

```
motion_night_outdoor:
   sensors:
      - group.house_exterior_activity
   entities: 
      - switch.outdoor_sidedoor_switch
      - switch.outdoor_front_switch
      - light.lower_patio_level
#      - group.outdoor_lights
   delay: 600
   sensor_type: duration
   start_time: sunset 
   end_time: sunrise 

```
