### ISSUE TITLE
FEATURE: Addition of a Constrain mode based on template condition (as opposed to start/end time)

### ISSUE THREAD

**Issue by danobot** [danobot/entity-controller#126]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Currently, we can define `start_time` and `end_time` to disable EC at certain times. It would be better to create a generic implementation such thatother types of schedules can be supported. This issue to support schedules based on a HA template condition.
If the conditino evaluates to true, the EC instance is operating. 
if the template condition is false, the EC instance is in `constrained` mode.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by brahmafear** [comment]
Bump.  Was going to add a feature request specifically for this.  

Use case:  I currently use a light sensor in the room to determine if the motion lights should activate.  Ie, if the room is already bright, no need to turn on the motion light.  

Current workaround would be to create a separate template sensor which watches my light sensor and switches to ON when light value is above a threshold, but it would be nice to have this functionality without the extra entity.

**Comment by danobot** [comment]
How would the sample configuration below work with your use case? Im thinking of ways to implement this.

```
 ec_issue_126:
    sensor: sensor.motion_sensor
    entity: 
      - light.kitchen_lights
    delay: 10 
    schedule:
      morning:
        platform: time
        start: 7:00:00
        end: 10:00:00
      room_lit:
        platform: template
        template: {{ states('light.room_light').state }}
```

**Comment by danielbrunt57** [comment]
> How would the sample configuration below work with your use case? Im thinking of ways to implement this.
> The schedule determines whether EC is in constrained state. For example, during the day it is constrained. Likewise, when room light is on it is also constrained.
> Should EC be constrained if ANY schedule is constrained? Or only when ALL schedules are constrained?
> 
> ```
>  ec_issue_126:
>     sensor: sensor.motion_sensor
>     entity: 
>       - light.kitchen_lights
>     delay: 10 
>     schedule:
>       day:
>         platform: time
>         start: sunset
>         end: sunrise
>       room_lit:
>         platform: template
>         template: {{ states('light.room_light').state }}
> ```

My vote would be for ANY if we have to choose one.
Would something like this be possible though?
`    schedule:
      logic: [any|all]
      day:
        platform: time
        start: sunset
        end: sunrise
      room_lit:
        platform: template
        template: {{ states('light.room_light').state }}`

**Comment by brahmafear** [comment]
Agree on constraint if **any** schedule matches - though with templates now providing a condition for constraint, maybe "schedule" isn't the best term.  

Modifying your example - my use case would be something like this.

```
 ec_issue_126:
    sensor: sensor.motion_sensor
    entity: 
      - light.kitchen_lights
    delay: 10 
    schedule:
      day:
        platform: time
        start: sunrise
        end: sunset
      room_lit:
        platform: template
        template: {{ states('sensor.light_level').state|int > 30 }}
```
So EC would be in constrained state during daylight or when the light level in the room is already bright.  (This would have repercussions beyond the scope of this feature request as the action of the EC would change the constraint condition - but that's a different issue.)

But the idea is the same, if the light level is already bright, no need for the EC to act.

**Comment by danobot** [comment]
I like this one. Note renaming of `schedules` to be `constraints`.
```
    constraints:
      logic: [any|all]
      day:
        platform: time
        start: sunset
        end: sunrise
      room_lit:
        platform: template
        template: {{ states('light.room_light').state }}
```

The biggest problem here is implementing templates into this component. I tried before and faced blockers. No one has been able to help on that problem. See this [branch](https://github.com/danobot/entity-controller/issues/150#issuecomment-687579863).
