### ISSUE TITLE
FEATURE: Dim lights before switching them off (staged dimming when no motion detected)

### ISSUE THREAD

**Issue by chbndrhnns** [danobot/entity-controller#127]
**Is your feature request related to a problem? Please describe.**
I am using the EC since today to control zigbee lights that were before controlled by Deconz. Its webapp supports staged dims of the lights when no motion is detected.

**Describe the solution you'd like**
I can set multiple timeouts with different brightness levels, something like:

```yaml
stages:
  full:
    brightness: 100
    duration: 180
   half:
     brightness: 50
     duration: 90  
```

**Describe alternatives you've considered**
The night mode provides something similar but it is also limited to one brightness setting.

**Additional context**
