### ISSUE TITLE
from active_timer to overridden

### ISSUE THREAD

**Issue by jacusuh** [danobot/entity-controller#132]
## Description
Transition from active_timer to overridden desn't turn off entity.

## Configuration
```yaml
entity_controller:
  tv_light:
    sensor: 
      - binary_sensor.tvroom_move
    entity: 
      - switch.tvroom_light
    delay: 300
    overrides:
      - binary_sensor.movie_paly
```

## Steps to reproduce
Triger motion, paly movie afterwhile .

### Expected behavior
Turn off entity

### Actual Behaviour
Entity stay in turned on state

## Version
Installed: v5.0.1
