### ISSUE TITLE
trigger_on_(de)activate not working in night mode

### ISSUE THREAD

**Issue by Friedrieck** [danobot/entity-controller#135]
## Description
The parameter `trigger_on_activate` (and likely so `trigger_on_deactivate`) does not work in the `night_mode`.
## Configuration
```
escalier_bas:                              
  sensor: binary_sensor.vestibule  
  entity: input_boolean.escalier_bas 
  trigger_on_activate: scene.escalier_bas_on 
  trigger_on_deactivate: scene.escalier_bas_off
  delay: 120                                
  block_timeout: 120
  start_time: sunset - 00:30:00   
  end_time: sunrise + 00:30:00  
  night_mode:
    delay: 60
    block_timeout: 30
    trigger_on_activate: scene.escalier_bas_on_nuit            
    trigger_on_deactivate: scene.escalier_bas_off
    start_time: '23:00:00'                  
    end_time: '06:30:00'                   
```

## Steps to reproduce
Test by calling `trigger_on_activate` in the night mode section of an EC configuration.

### Expected behavior
The `trigger_on_activate` instruction inside the night mode section should be executed if present.

### Actual Behaviour
The `trigger_on_activate` instruction inside the night mode section seems to be ignored, the instruction of the 'normal' mode is called instead.

## Logs
Not necessary. 

## Version
Latest version used.
