### ISSUE TITLE
override light should restore previous situation

### ISSUE THREAD

**Issue by jokerigno** [danobot/entity-controller#137]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi,

I'm using this automation:

```
entity_controller:
  jack_lamp:
    sensor: binary_sensor.studio
    entity: light.jack_lamp 
    override: light.studio
    start_time: sunset - 00:30:00
    end_time: sunrise + 00:30:00
```

it turns on a lamp is motion is detected in the room. It's ok mostly of time but in my opinion something is missing. It happens that I walk into the room and switch on the main light (light.studio), this leave jack_lamp still on but it is useless.

Solution can be that if the override switch goes to on the entity light goes off again.

This should be possible?
