### ISSUE TITLE
Entity that becomes unavailable during ON state is not turned off

### ISSUE THREAD

**Issue by pluskal** [danobot/entity-controller#138]
I have the following setup with led strip light (ESPHome), communicating with HA over MQTT.

```
light1:
  sensor: 
    - binary_sensor.motion1
    - binary_sensor.motion2
  entity: light.light1
  delay: 60 
  block_timeout: 3600
  start_time: sunset - 01:00:00
  end_time: sunrise + 01:00:00
  service_data:
    brightness: 255
  night_mode:
    delay: 60
    service_data:
      brightness: 150
    start_time: '22:00:00'                  # required
    end_time: '07:00:00'                    # required
```

In case that `light` is activated, and during the ON period becomes `unavailable`, it is never turned off. MQTT persists the ON message and the light when boots up is turned ON.

I expect that it is normal behavior to store the last entity state in MQTT so it survives HA reboot and component reboot as well.
