### ISSUE TITLE
active_stay_on state is not clearing

### ISSUE THREAD

**Issue by dexn** [danobot/entity-controller#164]
## Description
After a day or 2 of working properly, the active_stay_on state doesn't clear and causes it not to activate the next day. I have EC overridden by an input boolean which is turned on and off by an automation at 5am and when the sun angle is at 7.5 degrees.

<img width="281" alt="EC active_stay_on stuck" src="https://user-images.githubusercontent.com/2460478/86840881-94d1a600-c0e6-11ea-9c49-ed34a92dc262.png">

I have also tried to manually change the state with the services `entity_controller.set_stay_off` but it didn't do anything.

## Configuration
**EC Config**
```yaml
friendly_name: "Morning Motion"
sensors:
  - binary_sensor.kitchen_motion_sensor
  - binary_sensor.toilet_motion_sensor
entities:
  - scene.5am_lights
state_entities:
  - light.kitchen_1_light
  - light.kitchen_2_light
stay: true
overrides:
  - input_boolean.motion_morning
```

**Automations**
```yaml
alias: 5AM
trigger:
  platform: time
  at: '05:00'
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.motion_kitchen
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.motion_morning
```

```yaml
alias: Sunrise
trigger:
  platform: numeric_state
  entity_id: sensor.sun_angle
  above: '7.5'
condition:
  condition: time
  after: '03:00'
  before: '09:00'
action:
  - scene: scene.sunrise_lights
```

**Scenes**
```yaml
name: 5AM Lights
entities:
  light.hallway_light:
    state: 'on'
    white_value: 127
  light.kitchen_light:
    state: 'on'
    white_value: 127
  light.living_room_light:
    state: 'on'
    white_value: 127
  light.sunroom_light:
    state: 'on'
    brightness: 255
    rgb_color:
    - 255
    - 218
    - 108
```

```yaml
name: Sunrise Lights
entities:
  input_boolean.motion_morning:
    state: 'on'
  input_boolean.motion_night:
    state: 'on'
  input_boolean.motion_kitchen:
    state: 'on'
  light.hallway_light:
    state: 'off'
  light.kitchen_light:
    state: 'off'
  light.toilet_light:
    state: 'off'
  light.laundry_light:
    state: 'off'
  light.sunroom_light:
    state: 'off'
  light.living_room_light:
    state: 'off'
```

### Expected behavior
When the override input boolean turns on, EC should should respond appropriately.

### Actual Behaviour
EC seems to get stuck on active_turn_on

## Version
v6.0.0
