### ISSUE TITLE
State of EC hangs on active

### ISSUE THREAD

**Issue by zarya** [danobot/entity-controller#169]
<<< Do not delete the following template headers. All information must be filled in because we need it to analyse the problem. Your issue will be auto closed without this information.
Before opening a new issue, please read the documentation and search for keywords relating to your problem. Since this is an open source project expect to be involved in the issue resolution because we depend on your support. >>>

## Description
The EC hangs on active
![image](https://user-images.githubusercontent.com/387694/89000964-06bd9980-d2f9-11ea-9165-6d526a197dc6.png)
You can see in the next screenshot the motion was triggered much more then the EC components tells
![image](https://user-images.githubusercontent.com/387694/89000996-16d57900-d2f9-11ea-8f20-dd39c1b8539d.png)

I created a second EC (on a different motion sensor) and that works fine. This one uses a Ikea zigbee motion sensor.

## Configuration
```
motion_wc:
  sensor: binary_sensor.0x000b57fffe26df68_occupancy
  entity: light.wc
  delay: 300
  service_data:
    rgb_color: [160,120,0]
    brightness: 200
  night_mode:
    service_data:
      rgb_color: [255,0,0]
      brightness: 80
    start_time: sunset + 00:30:00
    end_time: sunrise - 00:30:00
```

## Steps to reproduce
It works for a while and then stops working

### Expected behavior
According to docs it should not stay on active long.

## Logs
Hard to make logs since it does not happen instant

## Version
Home Assistant 0.113.2
EC installed via HACS and up to date.
