### ISSUE TITLE
EC gets blocked after backoff is triggered

### ISSUE THREAD

**Issue by pippyn** [danobot/entity-controller#185]
<<< Do not delete the following template headers. All information must be filled in because we need it to analyse the problem. Your issue will be auto closed without this information.
Before opening a new issue, please read the documentation and search for keywords relating to your problem. Since this is an open source project expect to be involved in the issue resolution because we depend on your support. >>>

## Description
The EC gets blocked after a backoff is triggered. (this also happens with and without night_mode)
I also tried setting the grace_period higher without success.
![image](https://user-images.githubusercontent.com/7591990/92561849-402ce180-f275-11ea-8683-f14d81920cc5.png)

## Configuration
```
overloop:
  sensor: 
    - binary_sensor.overloop
    - binary_sensor.trap_naar_overloop
  entity: light.overlooplamp
  grace_period: 10
  delay: 120
  backoff: true
  backoff_factor: 1.2
  backoff_max: 600
  service_data:
    brightness: 255
    transition: 3
  service_data_off:
    transition: 3
  night_mode:
    delay: 60
    service_data:
      brightness: 20
      transition: 3
    service_data_off:
      transition: 3
    start_time: '23:30:00'
    end_time: '07:00:00' 
  overrides:
    - binary_sensor.light_outside
    - input_boolean.motion_sensor_off
```
## Steps to reproduce
trigger the sensor. Wait a few seconds and trigger the sensor again. 

### Expected behavior
There was no manual input so the EC shouldn't be set to blocked.

## Logs
Provide logs at DEBUG level. 

## Version
v8.0.0
