### ISSUE TITLE
Help with closet doors

### ISSUE THREAD

**Issue by broyuken** [danobot/entity-controller#186]
I have an automation that will turn on a closet light when the closet door is opened, turn it off when it's closed and also turn it off if left open for 5 minutes. I was hoping to move this over to EC but cannot find a way to handle the turning off the light when the door closes part. The way I'm reading the readme leads me to believe the light would turn off when the door closes, but only after the timer has expired if I set it as a `sensor_type: duration`. Is this doable with the current version of EC, if not would it be possible to add this functionality to turn off the light once a binary sensor is turned off? Or should I just keep it as an automation?

```
- id: automaticdoorlights
  alias: Lights - Doors
  description: ''
  trigger:
  - entity_id: binary_sensor.charlottes_closet_door_sensor, binary_sensor.justins_closet_door_sensor,
      binary_sensor.isabelas_closet_door_sensor
    platform: state
  - entity_id: binary_sensor.charlottes_closet_door_sensor, binary_sensor.justins_closet_door_sensor,binary_sensor.isabelas_closet_door_sensor
    for: 0:05:00
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data_template:
      entity_id: light.{{ trigger.to_state.object_id.replace('_door_sensor','_light')
        }}
      transition: 2
    service_template: light.turn_{{ trigger.to_state.state if trigger.for == None
      else 'off'}}
```
