### ISSUE TITLE
Issue with sensor_resets_timer

### ISSUE THREAD

**Issue by broyuken** [danobot/entity-controller#196]
<<< Do not delete the following template headers. All information must be filled in because we need it to analyse the problem. Your issue will be auto closed without this information.
Before opening a new issue, please read the documentation and search for keywords relating to your problem. Since this is an open source project expect to be involved in the issue resolution because we depend on your support. >>>

## Description
dle -> Active Timer -> [timer started] ... [timer expires] ... (sensor goes to off) ... [timer restarted] ... (sensor goes to on)... [timer expires] -> Idle -> light shuts off

When the sensor_resets_timer: true resets the timer one last time, if the motion sensor gets triggered again, it does not restart the process back to active timer, it just continues the last timer. When the timer goes off, even though there is still motion in the room and the sensor is on, the light turns off. This happened to us last night while we were eating dinner which was less than pleasant. 

## Configuration
Include configuration of affected entity.
```
  ec_chandelier_light:
    sensor: binary_sensor.kitchen_motion
    entity: light.chandelier
    delay: 600
    sensor_type: duration
    sensor_resets_timer: true
    service_data:
      brightness_pct: 50
    service_data_on: 
      transition: 2
    service_data_off: 
      transition: 120
    night_mode:
      delay: 60
      service_data:
        brightness_pct: 15
      start_time: '23:00:00'
      end_time: 'sunrise'
    backoff: true
    backoff_factor: 1.1
    backoff_max: 3600
    behaviours:
      on_enter_overidden: "off"
      on_enter_constrained: "off"
    overrides:
     - sensor.sunny_day
     - input_boolean.ec_disable
```
## Steps to reproduce
Trigger motion (sensor turns on)
Motion stops (sensor turns off)
Timer expires
Timer restarts because of sensor_resets_timer: true
Trigger motion
observe light turning off after timer set by sensor_resets_timer: true

### Expected behavior
Trigger motion (sensor turns on)
Motion stops (sensor turns off)
Timer expires
Timer restarts because of sensor_resets_timer: true
Trigger motion
***EC should go back into active timer state,**
Light stays on
Happy wife

### Actual Behaviour
Trigger motion (sensor turns on)
Motion stops (sensor turns off)
Timer expires
Timer restarts because of sensor_resets_timer: true
Trigger motion
***EC continues previous timer from sensor_resets_timer: true**
Light turns off
Get angry look from wife

## Version
If you are not using the latest version, please upgrade first.
v9

**Comment by danobot** [comment]
hmm, do you have any suggestion where the problem might be in code?

**Comment by broyuken** [comment]
I'm not a coder but I'll see if I can poke around and see where it may be broken.

**Comment by broyuken** [comment]
So I think this may be a different issue that I originally thought. I have my lights turn off slowly over 2 minutes after the timer resets back to idle so I'm not thrown into darkness immediately and I can wave my arms to turn them back on. However, when I do this with EC the lights are still "technically on" but the sensor is idle so it goes into blocked mode. 

Could we make an override where blocked mode is ignored for a configurable amount of time after a sensor goes from active_timer to idle? That way, when I notice the lights start to dim I can move and restart the active_timer without the light going into a blocked state? Something like ignore_blocked_timer ? 
```
Idle -> Active Timer -> [timer started] ... [timer expires] ... (sensor goes to off) ... [timer restarted] ... [timer expires] ... (2 minute transition ) ... -> [ignore_blocked_timer] -> (sensor goes to on) -> light goes back on -> [timer restarted] 
```

Or could you make it so that it detects if there is a transition in the config when turning off it extends the timer for that much longer?
```
  ec_chandelier_light:
    sensor: binary_sensor.kitchen_motion
    entity: light.chandelier
    delay: 600
    sensor_type: duration
    sensor_resets_timer: true
    service_data:
      brightness_pct: 50
    service_data_on: 
      transition: 2
    service_data_off: 
      transition: 120
```
So in this case, the timer is 10 minutes, with a 2 minute transition, so the timer would actually be set to 12 minutes in the background?
