### ISSUE TITLE
Block on manual off also

### ISSUE THREAD

**Issue by iamandymcinnes** [danobot/entity-controller#197]
## Description
When you manually turn a light off the state is set to idle, however if you want to stop EC taking control of the light you can't. An example would be a motion event triggers a light to be turned on, you manually turn this off for example you are surprising someone for their birthday (i.e. something outside of your normal automation routines like going to bed early). When motion is detected again, as the state is now idle and not blocked following your manual intervention, EC will turn the light back on when motion is detected.

Another example could be heating controls, I have a minimum temperature set and a schedule, however it's summer and I'm hot, so I manually turn the heating off. However the schedule time is triggered or the minimum temperature say (17 degrees) triggers and the heating turns on. A good example of this being a problem would be if you had air conditioning as well, as the two system could compete, i.e. I set my air conditioner to 16 degrees, which in turn triggers the heating to come on as the minimum temperature has been triggered.

## Configuration
I've just included a lounge light and lamp as an example, the idea being someone may turn the main light off when watching TV for example.

```
lounge_light_controller:
  friendly_name: "Lounge Light Controller"
  sensors: 
    - binary_sensor.lounge_motion
  entities:
    - light.lounge
  delay: 120
  backoff: true
  backoff_factor: 1.1
  backoff_max: 600
  start_time: 'sunset - 01:00:00'
  end_time: '19:00:00'
  block_timeout: 10800

lounge_lamp_controller:
  friendly_name: "Lounge Lamp Controller"
  sensors: 
    - binary_sensor.lounge_motion
  entities:
    - light.lounge_lamp
  delay: 120
  backoff: true
  backoff_factor: 1.1
  backoff_max: 600
  start_time: '19:00:00'
  end_time: '23:00:00'
  block_timeout: 10800

```
## Steps to reproduce
Create an entity with the config above

### Expected behavior
1) Create an entity with the config above
2) Set the new block_manual_off property to True from default of False)
2) When triggered by motion light turns on (state moves from idle to active)
3) Manually turn light entity off (state is blocked or something else to identify a manual off event)
4) Motion triggers again but light remains off

### Actual Behavior
1) Create an entity with the config above
2) When triggered by motion light turns on (state moves from idle to active)
3) Manually turn light entity off (state moves from active/constrained/blocked back to idle)
4) Motion triggers again light turns on
## Logs
Provide logs at DEBUG level. 

## Version
If you are not using the latest version, please upgrade first.
latest (9.0.0)
