### ISSUE TITLE
Random issues with lights coming on when they shouldn't and not when they should

### ISSUE THREAD

**Issue by iamandymcinnes** [danobot/entity-controller#211]
## Description
I've got most of my lights setup so they come on between sunset and sunrise, with an input_boolean that I use to turn them off when I got to bed. My good night scene, sets my input_boolean.disable_entity_controlled_lighting to true when I go to bed and then the morning scene sets it to false.

I've noticed in the middle of the night the light will come on randomly, some times motion triggers it to come on through the night and at other times motion doesn't trigger it as expected. Also other times such as in the evening the light doesn't come when it should, but at other times will. 

I've confirmed my input_boolean is set as I expected it to be i.e. false during the day until I run my night scene which sets it false throughout the night.

## Configuration
```
bedroom_light_controller:
  friendly_name: "Bedroom Light Controller"
  sensors: 
    - binary_sensor.bedroom_motion
  entities:
    - input_boolean.disable_entity_controlled_lighting
    - light.bedroom
  state-entities:
    - light.bedroom
  delay: 120
  backoff: true
  backoff_factor: 1.1
  backoff_max: 600
  start_time: 'sunset'
  end_time: 'sunrise'
  block_timeout: 1800
```

## Steps to reproduce

1. Create an input select called: input_boolean.disable_entity_controlled_lighting
2. Add the config above
3. Set the input boolean to true (i.e. to simulate night)
4. Trigger motion

## Expected behavior
This is how the component _should_ work:

1. When the input_boolean is true motion should not trigger the light to come on
2. When the input_boolean is false motion should trigger the light to come on

## Actual Behavior
This is what _actually_ happened:

1. Sometimes the light will come on when the input_boolean is set to true when it shouldn't
2. Sometimes the light won't come on when the input_boolean is set to false when it shouldn't

## Logs

```
Provide logs at DEBUG level. 
```

## Version
```
If you are not using the latest version, please upgrade first. "Latest" is not a version, please provide the exact version string.
```
9.1.0
