### ISSUE TITLE
Override Entity ('NoneType' object has no attribute 'state') does not exist.

### ISSUE THREAD

**Issue by danielbrunt57** [danobot/entity-controller#212]
<<< Override Entity ('NoneType' object has no attribute 'state') does not exist >>>

## Description
The entity for my fireplace light control has three override entities via the `overrides:` entry. 
This seems to create an error in HA logs at startup.

## Configuration
```
  front_porch_light_control:
    friendly_name: Front Porch Light Control
    sensor: binary_sensor.lumi_lumi_sensor_motion_aq2_a2154d04_ias_zone
    sensor_type: duration
    entity: switch.nzw30_smart_switch_switch
    start_time: sunset - 00:10:00
    end_time: sunrise + 00:10:00

  fireplace_light_control:
    friendly_name: Fireplace Light Control
    sensor: binary_sensor.lumi_lumi_sensor_motion_aq2_68988604_ias_zone
    sensor_type: duration
    entity: switch.switchlinc_relay_dual_band_1f_b7_25
    start_time: sunset - 00:30:00
    end_time: sunrise + 00:30:00
    overrides:
      - switch.switchlinc_relay_dual_band_1f_b3_c5
      - switch.appliance_module_zl7201us_switch
      - media_player.living_room_tv

  bedroom_lights_control:
    friendly_name: Bedroom Lights Control
    sensor: binary_sensor.lumi_lumi_sensor_motion_aq2_19bc3f05_ias_zone
    sensor_type: duration
    state_attributes_ignore:
      - color_temp
      - brightness
    entity: group.bedroom_lights
    override: 
      - input_boolean.bedroom_motion_disabled
    state_entities:
      - light.bedroom_lamp_1_level_light_color_on_off
      - light.bedroom_lamp_2_level_light_color_on_off
    start_time: sunset - 00:30:00
    end_time: sunrise + 00:30:00

  office_lights_control:
    friendly_name: Office Lights Control
    sensor: binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone
    sensor_type: duration
    sensor_resets_timer: True
    entity: light.osram_lightify_a19_tunable_white_ef4a0900_level_light_color_on_off
    state_attributes_ignore:
      - color_temp
      - brightness
    delay: 240
```

## Steps to reproduce

1. Create an entity with multiple overriding entities via `overrides:`

## Expected behavior
This is how the component _should_ work:

1. No error should be created in HA logs 

## Actual Behaviour
This is what _actually_ happened:

1. An HA error occurred 

## Logs

```
Logger: custom_components.entity_controller.fireplace_light_control
Source: custom_components/entity_controller/__init__.py:703
Integration: Entity Contoller (documentation)
First occurred: 3:55:11 PM (2 occurrences)
Last logged: 3:55:12 PM

Configuration error! Override Entity ('NoneType' object has no attribute 'state') does not exist. Please check for spelling and typos.
```

## Version
```
v9.1.0
```
