### ISSUE TITLE
Different entities on day/night

### ISSUE THREAD

**Issue by haavardNO** [danobot/entity-controller#213]
I am not sure if this is a feature request or bug report, since I dont know if EC is suppose to do what I am trying to do.

I have 5 lights in my bedroom.
2 night stand lights
1 led light under bed
1 chandelier 
1 wardrobe light

What I want to do:
Day:
Turn on night stands, led under bed and wardrobe light.

Night:
Turn on only led under bed (rgb value).

Watch all the 5 lights for potential block out etc...

I have tried several approaches, but the below is the current. Any reason for this to not work? When the sensor is triggered it only turns on the listed entities.

```
  motion_light_mb:
    sensor:
      - binary_sensor.ms_motion_master_bedroom
    entities:
      - light.hue_color_candle_1
      - light.hue_color_candle_1_2
      - light.extended_color_light_1
      - light.soverom_tak
    trigger_on_activate: script.day_light_mb
    trigger_on_deactivate: light_off_mb
    delay: 300
    sensor_type: duration
    sensor_resets_timer: True
    block_timeout: 3600
    night_mode:
      delay: 60
      trigger_on_activate: script.night_light_mb
      trigger_on_deactivate: light_off_mb
      start_time: "17:00:00"
      end_time: "06:00:00"
```
