### ISSUE TITLE
FEATURE: Enhance block mode

### ISSUE THREAD

**Issue by floris-b** [danobot/entity-controller#230]
## Description
when you have multiple control entities:
- EC should turn on the control entities that are off and not go in block mode because one of them is on
- turn off the control entities that where off at the start, or turn them all off or turn off specific ones that where on with the ones that where off
- have a config option for each control entity for block behavior and turn off behavior

## Example use case
multiple EC's with overlapping control entities

**Comment by floris-b** [comment]
maybe this can be added in:
  def _state_entity_state(): check the config option for each control entity and add an attribute
  def turn_off_control_entities(): check the attribute which ones to turn off
thinking to add a transition but probably that is over-complicating things?

**Comment by danobot** [comment]
Adding a transition is almost never the solution. This use case is currently not supported because the way EC is set up doesnt lend itself to entity level rules like that. It also goes against the requirements where entites that are already being controlled should not be interfered with.

**Comment by floris-b** [comment]
I do not think it is against the original 3.1 core requirements if you have the option, just like block_timeout is not if you have the choice and defaults to the core requirements
For example:
Outside door has a sensor, I want the light to turn on outside and in the hallway, but the hallway light is already on but I still really need the outside light to turn on
I was thinking of adding two config options to every control entity:
- CONF_NOBLOCK
- CONF_FORCEOFF
and checking those in the two functions I mentioned, do you think it is going to break something else?

Answered my own question, its already broken with the following config, EC stays in block mode while all control entity are off

```
motion_stairs:
  sensor: input_boolean.pirstairs
  entity:
    - input_boolean.lighthallway
    - input_boolean.lightstairs
  sensor_type: duration
  friendly_name: Motion Stairs
  delay: 10

motion_outside:
  sensor: input_boolean.piroutside
  entity:
    - input_boolean.lighthallway
    - input_boolean.lightoutside
  sensor_type: duration
  friendly_name: Test Motion Buiten
  delay: 10
```
