### ISSUE TITLE
Overrides being ignored

### ISSUE THREAD

**Issue by tvaughan73** [danobot/entity-controller#231]
## Description

Overrides not applied when entity associated with override is in on state prior to start time.
Configuration below is triggered by a motion detector and should be active during the start-end times.  This should be overridden if TV is on.  

This works as intended if media_player.living_room_tv is in 'off' state after start time.  

If media_player.living_room_tv is in 'on' state when start time occurs the override is ignored.

When start time occurs does EC look at current state of overrides?

## Configuration
```
entity_controller:
  motion_light:
    sensor: binary_sensor.ecolink_motion_detector_sensor
    entities:
      - light.living_room_spot_lights
      - light.catwalk_lights
    start_time: sunset + 00:10:00
    end_time: sunrise - 00:30:00
    delay: 300
    service_data:
      brightness: 100
    overrides:
      - media_player.living_room_tv
```
## Version
```
v9.2.0
```
