### ISSUE TITLE
Param support in Helper Functions

### ISSUE THREAD

**Issue by maxlyth** [danobot/entity-controller#249]
## Add param support to helper functions
It seems illogical that param support is specifically unavailable when calling helper functions. This makes it impossible to use a generic script that handles motion where multiple EntityControllers can pass a differentiating parameter to that script. An example might be to pass the room name to the helper function and to the script which could in turn initiate a scene using the same parameter.

## Configuration
```
  trigger_on_activate: script.room_lights_motion
  trigger_on_deactivate: script.room_lights_off
  service_data:
    variables:
      room: "bedroom"
  service_data_off:
    variables:
      room: "bedroom"
```
