### ISSUE TITLE
Overrides not working (probably because sensor was idel/active?)

### ISSUE THREAD

**Issue by Klagio** [danobot/entity-controller#26]
Now its 23:00:00, the input_boolean is on (I checked), but the component is idle, and with a movement all the lights go ON.

My goal is: I am sitting in my living room with lights ON, I want to turn ON my projector, and turn OFF the lights, since I have the lightingsm component for triggering the lights with motion, I need to turn this feature OFF (put manually in front-end an input_boolean to ON, and this input_boolean is in ovveride section) also WHILE sitting in the living room.

Maybe lightingsm did not work because when I turned ON the input_boolean (the override) the component was active (idle or active_timer)?

```

  dining_room_evening: 
    sensors: 
          - binary_sensor.pir_living_two
          - binary_sensor.pir_living_four
          - binary_sensor.pir_stairs_up
          - binary_sensor.pir_stairs_down
    entities: 
          - light.chandelier_one_2
          - light.chandelier_two_2
          - light.chandelier_three_2
    start_time: '17:00:00'   # change when sunset will work
    end_time: '23:59:59'
    delay: 360
    sensor_type_duration: True
    overrides:
          - input_boolean.motion_dinimg_evening
```
