### ISSUE TITLE
Entity controller becoming blocked after turning on

### ISSUE THREAD

**Issue by Inlustra** [danobot/entity-controller#265]
## Description
As described in the title, the act of turning on the motion light via the shelly switch causes the motion light to become blocked.
I've added an image of the logbook below to describe the issue I'm seeing.
I have no doubt that this could be due to something my end, but I'd really appreciate some guidance!

It's worth mentioning 
- Toggling the `input_boolean.pir_override` on and off, clears the blocked state.
- Turning the `input_boolean.pir_override` on stops the switch from triggering at all, as expected. I mention this as my assumption then is that no other automation or inteference is turning the switch on
- Adding `sensor_type: duration` has the same behavior (Even though I imagine this is the correct thing to use?)

A bit more context:
I originally had this working via the default Shelly integrations and then migrated over to ShellyForHass, but I don't totally understand the difference in implementations here, my assumption is that they just work the same.

## Configuration
```
entity_controller:
  motion_light: # serves as a name
    sensor: binary_sensor.shelly_shellypro4pm_84cca87ef154_4_switch # required, [sensors]
    entity: switch.shelly_shellypro4pm_84cca87ef154_4 # required, [entity,entities]
    delay: 300
    start_time: sunset - 00:30:00 # required
    end_time: sunrise + 00:30:00 # required
    overrides:
      - input_boolean.pir_override

input_boolean:
  pir_override:
    name: PIR Override
    icon: mdi:clock-outline
```

![image](https://user-images.githubusercontent.com/2565465/167316695-c32e9db2-5ccb-4956-aeea-29430aa477e9.png)
