### ISSUE TITLE
Time Constraints input time update

### ISSUE THREAD

**Issue by dankarization** [danobot/entity-controller#281]
## Description
Now you can only use start_time and end_time as hardcoded variables or with sunset values. I think it will be even more useful to implement any datetime variables there. With this, user can easily change all values for entity controller at the same time through UI just changing 2 datetime variables.
Same is useful for night mode times.

## Configuration
```
motion_light_sun:
  sensor: binary_sensor.living_room_motion
  entity: light.table_lamp
  start_time: input_datetime.daylight
  end_time: input_datetime.nightlight
```

## Steps to reproduce
Well, none

## Expected behavior
Also none

## Actual Behaviour
Still none

## Logs
nope
```
Provide logs at DEBUG level. 
```
nope

## Version
```
9.5.2
```
