### ISSUE TITLE
Controller entity always entering `blocked` state - why?

### ISSUE THREAD

**Issue by nickdos** [danobot/entity-controller#307]
My controller entity is always going into the `blocked` state and I can't workout why this happens.

My YAML code:

```yaml
entity_controller:
  motion_garage_lights:
    sensor: 
      - binary_sensor.openclose_21
      - binary_sensor.motion_sensor_1
    entity: 
      - light.garage_light_1
      - light.garage_light_2
    delay: 300
    grace_period: 5
    start_time: '05:30:00'
    end_time: '22:30:00'
```

Here is the timeline of events:
 - 10:14:39 `binary_sensor.motion_sensor_1` goes from "Cleared" state to "Motion detected"
 - 10:14:39 `entity_controller.motion_garage_lights` goes from "idle" to "active_timer" (light turned ON)
 - 10:15:49 `entity_controller.motion_garage_lights` goes from "active_timer" to "blocked"
 - 10:16:41 `binary_sensor.motion_sensor_1` goes from "Motion detected" state to "Cleared"

At 13:05 `entity_controller.motion_garage_lights` is still in "blocked" state.

Note: `binary_sensor.openclose_21` has no activity during this time (remained in a "closed" state). The light entities only had state changed to ON once by the controller entity - no other changes of state occurred. I previously added the `grace_period` as per [another issue](https://github.com/danobot/entity-controller/issues/182), which suggested this change and a full HA restart was applied (one day ago).
