### ISSUE TITLE
If in constrained period and override is set it’s ignored when constraint ends 

### ISSUE THREAD

**Issue by jwelter1971** [danobot/entity-controller#31]
I have kids rooms set with a motion constraint to allow operating from 8am to 8pm.

I also have a override that comes on if bright enough we don’t need lights.

That override was tripped at 7:58am but when constraint ended at 8am it was ignored

I think we need to check override sensor state when entering and exiting constrained period?

**Comment by danobot** [comment]
This means that `override` state overrides all other states, including `constrained`. 
Easy to implement, but it is a bit confusing from user perspective to see the entity in `override` state when it should be `constrained`. Will investigate if what you suggested is feasable. I do not want to add if/else checks everywhere.

**Comment by jwelter1971** [comment]
Hi Danny I think constrained should (and does) have priority over any over-rides.  So when in constrained mode it's completely inactive.  That is currently how it works.

The only problem is when it exists constrained mode (and perhaps enter - not tested that specifically) if the trigger for an override is already set it seems to be ignored.  If I toggle that override state off/on outside of constrained mode what we expect happens; the lightings goes into overrides mode.

Set example here:

```
motion_connor_bedroom:
   sensors: 
      - binary_sensor.connor_pir_sensor
   entities: 
      - light.connors_ceiling_fan_light
   state_entities:
      - group.connors_bedroom_lights
   delay: 900
   sensor_type_duration: True
   start_time: '08:00:00' 
   end_time: '19:30:00' 
   overrides:
      - binary_sensor.auto_lights_override

```
