### ISSUE TITLE
example of "Custom State Strings"

### ISSUE THREAD

**Issue by blightniak** [danobot/entity-controller#315]
I'm using and ELK Alarm and motion is reported as "violated" and "normal".  Reading the documentation I assume I have to do a Custom State Strings and update DEFAULT_ON and OFF.

Can you give us an example.   

```
entity_controller:
  ec_kitchen_light:
    sensor: sensor.elkm1_kitchen_motion
    entity: switch.greenhouse_heat_plug
    delay: 3
```

Status of the ELK sensor from developer tools

```
[sensor.elkm1_kitchen_motion] - ElkM1 Kitchen motion

Normal

index: 19
physical_status: eol
logical_status: normal
definition: burglar_interior
area: 1
triggered_alarm: false
icon: mdi:alarm-bell
friendly_name: ElkM1 Kitchen motion

```
