### ISSUE TITLE
Add transition time to service_data

### ISSUE THREAD

**Issue by pippyn** [danobot/entity-controller#35]
Is it possible to add a [transition time](https://www.home-assistant.io/components/light/#service-lightturn_on) to service_data? I tried it with this config but it didn't work;
```yaml
  room:
    sensor: 
      - binary_sensor.motion_sensor
    entity_on: light.light1
    service_data:
      brightness: 255
      transition: 3
```
No errors in the log, it just ignores the transition.
Expected behaviour should be that the light turns from off to full brightness in 3 seconds.
