### ISSUE TITLE
Never returns to idle from blocked

### ISSUE THREAD

**Issue by isabellaalstrom** [danobot/entity-controller#39]
All entities have gone back to off, but the entity_controller is still blocked.

![image](https://user-images.githubusercontent.com/22006797/53681047-ec3a5780-3ce3-11e9-8723-5af55d0a01a7.png)
![image](https://user-images.githubusercontent.com/22006797/53681052-fe1bfa80-3ce3-11e9-8607-949150e50eb7.png)

config:
``` kids_nightlight:
  sensors:
    - binary_sensor.motion_playroom
    - binary_sensor.motion_oliwers_room
    - binary_sensor.motion_eliaz_room
    - binary_sensor.motion_lowas_room
    - binary_sensor.motion_bathroom
  entities:
    - switch.fibaro_system_fgs221_double_relay_switch_2x15kw_switch
    - light.playroom_lamp
  start_time: '20:00:00'
  end_time: '06:00:00'
  delay: 60
  overrides:
    - input_boolean.kids_nightlights_off

**Comment by jwelter1971** [comment]
I'm seeing the same thing with 3.1.1 with no config changes (not using the new features introduced).

It's occurring on 2 out of 15 entity_core instances; but nothing that unique about these two from the others.

It indicates it is blocked by the group.family..... defined in state entities.

See config here:

```
motion_family:
   sensors:
      - binary_sensor.ms_family_room_sensor
      - binary_sensor.family_room_pir_sensor
   entities:
      - light.family_room_lamps
   state_entities:
      - group.family_room_lights
   delay: 1800
   sensor_type_duration: True
   start_time: sunset - 00:30:00
   end_time: '23:30:00'
```
