### ISSUE TITLE
Did anything change recently: lights go from off to on, outside trigger period

### ISSUE THREAD

**Issue by Klagio** [danobot/entity-controller#41]
Now its 08:00 (outside the time of the configuration) and with motion the lights go from off to on (in plain day)

Until yesterday this was not happening

```

  dining_room_evening: 
    sensors: 
          - binary_sensor.pir_living_two
          - binary_sensor.pir_living_four
          - binary_sensor.pir_stairs_up
          - binary_sensor.pir_stairs_down
    entities: 
          - light.chandelier_one
          - light.chandelier_two
          - light.chandelier_three
    start_time: sunset    
    end_time: '23:59:59'
    delay: 360
    sensor_type_duration: True
    overrides:
          - input_boolean.motion_dining_evening
          - input_boolean.dining_stop_off

  dining_room_night: 
    sensors: 
          - binary_sensor.pir_living_two
          - binary_sensor.pir_living_four
          - binary_sensor.pir_stairs_up
          - binary_sensor.pir_stairs_down
    entity: light.chandelier_one
    service_data:
            brightness: 80
    start_time: '00:00:01'
    end_time: '07:00:00'
    delay: 65
    sensor_type_duration: True
    overrides:
          - input_boolean.motion_dining_night

```
