### ISSUE TITLE
Ability to use another entity state as input

### ISSUE THREAD

**Issue by kylerw** [danobot/entity-controller#44]
Use case is to have a slider in the UI to determine the delay or block_timeout.

something like:
```
    office_lights:
      sensors: 
        - binary_sensor.basement_multisensor_motion
        - light.office_light_level
        - light.office_lamp_level
      entities: 
        - light.office_light_level
        - light.office_lamp_level
      block_timeout: input_number.office_timout

```
