### ISSUE TITLE
Feature request: More flexible override entities

### ISSUE THREAD

**Issue by ugleatle** [danobot/entity-controller#46]
It would be nice if the override entities could be set per sensor, for instance if you want it to trigger on motion A, or (motion B if state C) (but A should be triggered no matter the state. You can make two motion lights that both have the same control entity. This however means that it can turn off to early if you have more than 1 sensor, because it will turn off when the first sensor has been off for 180 seconds, even if the second has been activated later.

It would also be nice if there was an "override on off", option in addition to the default "override on on", you can solve it with a input_boolean or something, but it would be easier and more elegant to be able to set it directly as a parameter.

**Comment by danobot** [comment]
It;s unlikely this will be implemented any time soon because it requires a major changes in how the code works and is set up.
What might help is templated overrides. Would that allow you to achieve what you need?

**Comment by ugleatle** [comment]
Thanks for the feedback. It is solvable with template sensors, just a bit more of a hassle, but I will just use that. Thanks for the great work, and maybe those features will appear some time in the future.

**Comment by danobot** [comment]
I use template sensors myself. It's important not to make the component too complex or reinvent the wheel. There is a home automation system whose features can be used together with this component.

>It would also be nice if there was an "override on off", option in addition to the default "override on on"

Try defining custom state strings, it is shown in the readme :) That might help as well.

**Comment by ugleatle** [comment]
Sorry to be bothering you, but I didn't understand how to use custom state strings to "Override on off", i tried: override_off_state: input_boolean.test, but that doesn't seem to do anything. So I am probably misunderstanding something fundamental.

**Comment by danobot** [comment]
You want override on OFF state? Then make the override state string contain "off" that way the override will be active when the override entity is off.
There is an example code snippet shown

**Comment by ugleatle** [comment]
I realize you have no obligation to perform tech support to slow users, but unfortunately i am not able to get it to work, based on the info in the chapter in the readme. If you can be bothered having a yaml-code example in the readme would be great.

**Comment by eifinger** [comment]
@ugleatle this is my configuration for your use case:

```yaml
---
entity_controller:
  oben_treppe_motion_trigger:
    sensor: binary_sensor.presence_stairs
    sensor_type: duration
    entity: light.upper_stairs_yeelight
    delay: 60
    override_states_on: "off"
    override_states_off: "on"
    overrides:
      - input_boolean.oben_treppe_motion_trigger
    service_data:
      brightness: 100
    night_mode:
      delay: 60
      service_data:
        brightness: 1
      start_time: 'sunset + 02:00:00'
      end_time: 'sunrise'

```
