### ISSUE TITLE
Enhance documentation for Exponential backoff

### ISSUE THREAD

**Issue by tiaanv** [danobot/entity-controller#50]
Can you please provide an example for appropriate config and use case for exponential backoff.
Want to try it on one or two lights to see how it works in practice.  Cant quite figure out from the documentation what the config options should be.  Do I still config a delay.... do I have separate expo for night mode?

**Comment by danobot** [comment]
You only need to define backoff: True to make this work. It will use default values. In my case, I added a maximim backoff value of 5 minutes. Each time the sensor is triggered, the timeout is reset and it increases each time it is reset up to a maximum of 5 minutes.

```
  mtn_lounge:
    entity: light.tv_led
    sensors:
      - binary_sensor.living_room_motion
      - binary_sensor.hallway_motion
    delay: 60
    backoff: True
    max_backoff: 300 
```
