### ISSUE TITLE
Entity ends up in perpetual constrained mode

### ISSUE THREAD

**Issue by justinmartin** [danobot/entity-controller#78]
Before opening a new issue, please read the documentation and search for keywords relating to your problem.

## Description

One of my entity controllers is switching to "constrained" after a day or so.  A restart gets it working again, but I can't figure out why it keeps happening.

<img width="377" alt="Screen Shot 2019-09-25 at 8 28 13 PM" src="https://user-images.githubusercontent.com/1242435/65651496-36fb2400-dfd4-11e9-891d-daabb2cb87b1.png">

## Configuration

```
motion_kitchen_main_lights:
  sensor: binary_sensor.kitchen_motion
  entity: switch.kitchen_main_lights
  start_time: sunrise
  end_time: "21:30:00"
  delay: 300
  block_timeout: 60
  overrides:
    - input_boolean.disable_kitchen_motion_lights
```

## Version
v4.0.4
