### ISSUE TITLE
How to pass a service_parameter that is templated?

### ISSUE THREAD

**Issue by jwelter1971** [danobot/entity-controller#8]
Hi, running 2.2.9 and working well!  Thanks for getting this going!  It's already removed a lot of complex automations.

One thing I am struggling with is in the past my automations for motion lights would use a brightness that was from a template sensor that monitored time of day and luminance to compute what the overall brightness should be.  This was done as follows:

```
   - service: light.turn_on
      data_template:
        entity_id: light.foobar
        brightness_pct: >-
          {{ states('sensor.target_brightness_inside')|int}}
```

How would I achieve this using the service parameters exposed by LightingSM?
