### ISSUE TITLE
Set override states per entity

### ISSUE THREAD

**Issue by eifinger** [danobot/entity-controller#91]
**Is your feature request related to a problem? Please describe.**

I have an override entity which should be on (control whether this automation should be on) and an override entity which should be off (we are not asleep).
I currently see no way to make that happen.

**Describe the solution you'd like**

If would be great to be able to configure this in the following way:

```yaml
overrides:
  - entity: input_boolean.bedroom_motion_trigger_app_switch
    override_states_on: "off"
    override_states_off: "on"
  - entity: input_boolean.all_asleep
    override_states_on: "on"
    override_states_off: "off"
```

**Describe alternatives you've considered**

I don't want to create a meta input boolean with an automation which sets this meta boolean based on the other two.

**Additional context**

N/A
