### ISSUE TITLE
Light or switch not turning on on motion event

### ISSUE THREAD

**Issue by rlust** [danobot/entity-controller#93]
Before opening a new issue, please read the documentation and search for keywords relating to your problem.

## Description
Lights not turning on when motion detected.
When I monitor the state of the entity controls they stay active once triggered.
Sensor stays on during motion detection/

## Configuration
Include configuration of affected entity.
```
# entity_controller:
motion_shop_light:
  sensor: binary_sensor.hai_motion_shop  # required, [sensors]
  sensor_type: duration
  entity: switch.16f884                 # required, [entity,entities]
  delay: 100                                # optional, overwrites default delay of 180s
motion_kitchen_light:
  sensor: binary_sensor.hai_motion_kitchen # required, [sensors]
  sensor_type: duration
  entity: light.3dfafe               # Kitchen Cans required, [entity,entities]
  delay: 120                                # optional, overwrites default delay of 180s

motion_walkway_light:
  sensor: binary_sensor.hai_motion_kitchen # required, [sensors]
  sensor_type: duration
  entity: light.7665076568c63ae4aa5c             # walkway Cans required, [entity,entities]
  delay: 120                                # optional, overwrites default delay of 180s
```

## Steps to reproduce
Start motion
**Expected behavior**

**Actual Behaviour**
Light does not turn on.
## Logs
Provide logs in DEBUG level. 
No logs
## Version
If you are not using the latest version, please upgrade first.
V 4.1.0
